let listP = [
  'The Mexico Car Market Is So Hot Even Volkswagen Posts Sales Gain',
  '|',
  "Canada's Renaissance Oil Eyes Onshore Joint Venture With Pemex",
  '|',
  'New York Times names several spots in Mexico as top 2016 places to visit',
  '|',
  "Drug Lord 'El Chapo' Has Been Caught, Says Mexican President",
  '|',
  'Museum of Fine Arts, Boston Acquires Frida Kahlo Work',
  '|',
  'Mexico Gas Summit set for San Antonio in April',
  '|',
  "Biden in Mexico: 'I almost feel obliged to apologize' for GOP rhetoric",
  '|',
  'Monarch Butterfly Migration Rebounds, Easing Some Fears',
  '|',
  'Alejandro González Iñárritu Wins Best Director Oscar Second Year In A Row',
  '|',
  'Mexico to Counter Republican Calls for Border Wall',
  '|',
  'Mexico Joins #HeForShe Campaign To Fight For Gender Equality',
  '|',
  'Mexico pays off water debt to Texas',
  '|',
  'Nafta May Have Saved Many Autoworkers’ Jobs',
  '|',
  'These Prints Made By Mexican Women Artists Are Hauntingly Beautiful',
  '|',
  'Ford to Build Plant in Mexico for Small Car Production in 2018',
  '|',
  "Mexico's Next Power Auction May Spur $4 Billion for Renewables",
  '|',
  "White House Increasingly Pushing Back Against Trump's Statements",
  '|',
  'Retiring in Mexico: More Affordable Than Ever',
  '|',
  'Mexico Has $13.6 Billion Surplus to Pay Debt, Boost Oil Fund',
];

$.hMarquee.marquee({
  el: $('.sliderp'),

  externalClass: 'marquee',

  list: listP,
  speedPeerSec: 40,
});

let listN = [
  'Wiretap allegedly shows a Mexican politician’s plan to buy a $58-million property in New York',
  '|',
  '800-yard-long drug tunnel found between Mexico and San Diego',
  '|',
  'Mexico Accused Of Torturing Suspects In Missing Students Probe',
  '|',
  'The Mexican Soldiers and Police Shown Torturing a Woman in a Video Will Face Trial',
  '|',
  "Mexico's Faltering Fight Against Corruption",
  '|',
  'Blocked By Mexico, Experts Fail To Solve Mystery Of 43 Missing Mexican Students',
  '|',
  "Bill O'Reilly Tells Former Mexican President Border Wall Is ‘Actually Humane’",
  '|',
  "Why America Can't Quit the Drug War",
  '|',
  'The Deeply Troubling Reason Women In Mexico City Are Riding Separate Subway Cars',
  '|',
  'Mexico warns of repercussions if remittances are blocked',
  '|',
  "An open wound': Mexico's missing women and girls",
  '|',
  'Mexico’s Financial Stability Seen at Risk as BNP Says Intervene',
  '|',
  "Cartels Are Displacing an Indigenous Group That's Lived in This Mexican State for Centuries",
  '|',
  'Body Count Points to a Mexican Military Out of Control',
  '|',
  '182 pounds of cocaine found on bus that traveled from Mexico to Wilmington',
  '|',
  'Voters in crime-plagued Tamaulipas head to ballot box in tight governor’s race',
  '|',
  'Report Accuses Mexico of Crimes Against Humanity in Drug War',
  '|',
  'Zetas drug cartel turned prison into private death camp, officials say',
  '|',
  'Mexico’s Peso Tumbles Most in Region on Global Growth Outlook',
  '|',
  'Treatment of immigrants in Mexico much worse than any other country',
  '|',
  'Mexico’s Cartels Are Much More Dangerous To Americans Than ISIS',
  '|',
  'Violent clashes between police and teachers union in Mexico leave 6 dead',
  '|',
  'Oil’s Broken Link to Mexico Peso Has BNP Warning of Bond Exodus',
  '|',
  'Sexual Abuse, Torture Used Against Women in Mexico Prisons, Arrests: Report',
  '|',
  'Killings of 2 Mexican mayors spur call for stepped up security',
  '|',
  "The Israeli Company That Fenced in Gaza Eyes Trump's Mexico Wall",
  '|',
  'Mexico President’s Approval Falls to 23% on Economy and Violence',
];

$.hMarquee.marquee({
  el: $('.slidern'),

  externalClass: 'marquee2',

  list: listN,
  speedPeerSec: 40,
});

let listB = [
  'Mexican E-Commerce Grows, but Requires Some Coaxing',
  '|',
  'Will Mexico Finally Agree to Send El Chapo to the U.S.?',
  '|',
  'What happens when you oppose illegal immigration, but like an illegal immigrant?',
  '|',
  'Nearing Tequila Crisis-Era Debt Levels Gives Mexico a Hangover',
  '|',
  'Anticorruption Efforts in Mexico',
  '|',
  'Mexico City Tightens Vehicle Restrictions After Pollution Alerts',
  '|',
  'The View From Mexico On Donald Trump',
  '|',
  'Mexico looks to set off a shale boom — will anyone bid?',
  '|',
  'Mexico’s President Has Changed His Mind and Will Attend the Big UN Drug Meeting After All',
  '|',
  'How this Mexican company plans to use drones to hunt for stolen cars',
  '|',
  'Mexican Stocks Rally With Peso as Clinton’s Odds Seen Improving',
  '|',
  'Why the head of the Republican Party in Mexico says he won’t vote for Donald Trump',
  '|',
  "Trump's challenge: Can he right the ship with Mexico?",
  '|',
  'President Enrique Peña Nieto phones Trump to start ‘new chapter’ in U.S.-Mexico relations',
  '|',
  'If Trump, The Dealmaker, Wants To Change NAFTA, He Has To Strike A Deal With Congress',
  '|',
  "Ford CEO warns Trump's 35 % car tariff would harm the economy",
  '|',
  'Trump’s fight against Made-in-Mexico could carry price on both sides of border',
  '|',
  "Mexico Makes A ‘Risky’ Last-Ditch Attempt To Save The Vaquita, The World's Smallest Porpoise",
  '|',
  "Canada still thinks Mexico belongs on its 'safe country' list for refugees",
];

$.hMarquee.marquee({
  el: $('.sliderb'),

  externalClass: 'marquee3',

  list: listB,
  speedPeerSec: 40,
});

let listI = [
  "Natalia Lafourcade Explains The Roots Of 'Hasta La Raíz'",
  '|',
  '1941: Mexico Reports New Nazi Plot',
  '|',
  'Pope Francis wonders if Mexicans will greet him with tequila',
  '|',
  'Affluenza Teen Seeks Asylum in Mexico',
  '|',
  '20 dead in bus crash in Mexico',
  '|',
  'It’s official: Astros vs. Padres in Mexico City in March',
  '|',
  'Independents launch Tijuana mayoral bids',
  '|',
  'New mosquito-borne virus Zika spreading in Caribbean',
  '|',
  'Mexico investigates Sean Penn’s $32,854 charter flight to meet El Chapo',
  '|',
  'Texans to play Raiders in prime-time game in Mexico',
  '|',
  '2 boys found after mother allegedly abducts them, takes them to Mexico',
  '|',
  'Trial for Border Patrol agent who shot and killed Mexican teenager moved to November',
  '|',
  'Femsa Follows Mexican Billionaire Carlos Slim in Euro Debt Debut',
  '|',
  'Cemex Swings to Profit in First Quarter',
  '|',
  "Mexico's Carlos Slim Puts Two Grandsons On Company Boards in Generational Transition",
  '|',
  'Tropical Storm Earl forms, heads for Mexico',
  '|',
  'Mexico’s Richest Man Wants a Three-Day Workweek',
  '|',
  'Hurricane Newton Heading for Mexico’s Baja Peninsula',
  '|',
  'Televisa’s Profit-Draining Cable Impasse Unlikely to Be Resolved',
];

$.hMarquee.marquee({
  el: $('.slideri'),

  externalClass: 'marquee4',

  list: listI,
  speedPeerSec: 40,
});
